# Yaml file containing the transformations between the the aruco markers and the frames of interest
# The transformations are expressed in the frame of the aruco markers
# define the transform of the frame wrt the aruco marker
resin_block:
  - aruco_id: 0
    frame_transform: 
      translation: [0.0, 0.0, 0.0] 
      quaternion: [0.0, 0.0, 0.0, 1.0] # [qx, qy, qz, qw] 
    name: "side1_T_object"
  - aruco_id: 1
    frame_transform: 
      translation: [0.0, 0.0, 0.0] 
      quaternion: [0.0, 0.0, 0.0, 1.0] # [qx, qy, qz, qw] 
    name: "side2_T_object"
  - aruco_id: 2
    frame_transform:
      translation: [0.0, 0.0, 0.0]
      quaternion: [0.0, 0.0, 0.0, 1.0]
    name: "side3_T_object"
  - aruco_id: 3
    frame_transform:
      translation: [0.0, 0.0, 0.0]
      quaternion: [0.0, 0.0, 0.0, 1.0]
    name: "side4_T_object"
  - aruco_id: 4
    frame_transform:
      translation: [0.0, 0.0, 0.0]
      quaternion: [0.0, 0.0, 0.0, 1.0]
    name: "side5_T_object"


